# Site settings
title: Un blog sur les usages de docker sur AWS
email: thomas.lacroix@cloudreach.fr
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://docker.tlacroix.info" # the base hostname & protocol for your site
twitter_username: ThomasLacroix
github_username:  thlacroix

# Build settings
markdown: kramdown
