# Site settings
title: Autour des containers
email: thomas.lacroix@cloudreach.fr
description: > # this means to ignore newlines until "baseurl:"
  Un blog autour des containers: présentations, actualité, didacticiels,
  tout ce que vous avez voulu savoir sur les technologies de containerisation,
  et leur intégration avec le monde DevOps.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://docker.tlacroix.info" # the base hostname & protocol for your site
twitter_username: ThomasLacroix
twitter_company_username: Cloudreach
github_username:  thlacroix

# Build settings
markdown: kramdown
highlighter: pygment
